package org.opends.guitools.statuspanel.browser.ui;

import org.opends.guitools.statuspanel.browser.ldap.Entry;

/**
 * Event generated by user actions in the browser tree.
 */
public class BrowseTreeEvent {

  private Entry entry;
  private int x;
  private int y;

  /**
   * Creates a new event.
   * @param entry associated with this event
   * @param x coordinate
   * @param y coordinate
   */
  BrowseTreeEvent(Entry entry, int x, int y) {
    this.entry = entry;
    this.x = x;
    this.y = y;
  }

  /**
   * The entry associated with the event.
   * @return the entry
   */
  public Entry getEntry() {
    return entry;
  }

  /**
   * The X coordinate of the user action.
   * @return int x coordinate
   */
  public int getX() {
    return x;
  }

  /**
   * The Y coordinate of the user action.
   * @return int y coordinate
   */
  public int getY() {
    return y;
  }

}
